spearhead-ea/island-keeper

package.json
src/app.ts

Fix issues that can be assigned before consul.session.create

Fix creating consul session issue

---

src/app.ts
src/spec/app-spec.ts

/v2/quota/:rpcName에서의 QuotaOption을 바꾸기 위해 
Consul의 해당 Key 값을 변경하는 기능 추가

QuotaOption을 변경하기 위한 Consul 처리

---

src/app.ts

change switchQuota

---

src/app.ts

Fix unregisterIsland that was working incorrectly

fix: wrong unregisterIsland

---

package.json

@types/blubird version was fixed for ts2.2
RELEASE_CANDIDATE

fix: @types/bluebird version fix

---

src/app.ts

Fixes a bug where the endpoint data broken when using the quota API.

fixed quota api bug

---

src/app.ts

https://github.com/spearhead-ea/island-keeper/pull/14
Reflect PR14 in lts version

fixed guard consul watch at lts version

---

src/app.ts

Change to support different kinds of quotas.

changed switchQuota

---

src/app.ts

do not registered the endpoint, If did not change it.

registerEndpoint checksum

---

src/app.ts

reflect master pr at 2.6-edge-lts
- https://github.com/spearhead-ea/island-keeper/pull/16
- https://github.com/spearhead-ea/island-keeper/pull/17

reflect pr16, pr17

---

package.json
src/app.ts

fixed json parding error (release-2.6-edge-lts)

Guard json parsing

---

src/app.ts

guard json parsing error  RELEASE_CANDIDATE

---

src/app.ts

https://github.com/spearhead-ea/island-keeper/pull/23
It reflects the test result.
The following issues have been found:
1. New endpoint registration failed
2. `Error: consul: kv.get: moved permanently`  consul Error message.
consul key should not be being a `/...`

fixed test result, release_candidate

---

src/app.ts

fix : wrong watch target key name

fix: watch bug

---

src/app.ts

Reverts spearhead-ea/island-keeper#26
it`s wrong

Revert "fix: watch bug"

---

src/app.ts

fix: consul key bug
if key name is capital letter, it is make two keys.

fix consul key bug RELEASE_CANDIDATE

---

src/app.ts

Add log consul connection info
http://git.sphd.io/support/stt-issues/issues/932

Feat.add.log.consul.connection.info

---

src/app.ts

- Added missing Promise.all
- saveEndpoint could end without awaiting endpoint registrations.

Fixed endpoints are not registered irregularly

---

package.json
src/app.ts

Even if there are many endpoints, should be registered all endpoints.

fix : many endpoint

---

src/app.ts

Even if there are many endpoints, should be registered all endpoints.

fix: If many endpoints

---

package.json
src/app.ts

Add the missing command.
The issues that do not watch on gateway-island

fix: missing command

---

package.json

http://git.sphd.io/support/stt-issues/issues/3095

fix: remove @types/winston

---

src/app.ts

fix cas does not work at first.
This issue can cause problems when starting a large number of instances at the same time if the consul is clean.

fix: cas bug at first
